/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectcos2103.Panel;

/**
 *
 * @author Lymven
 */
class SelectionSort {

    public Comparable[] selectionSort(Comparable[] theArray, int n) {
        for (int last = n - 1; last >= 1; last--) {
            int largest = indexofLargest(theArray, last + 1);
            Comparable temp = theArray[largest];
            theArray[largest] = theArray[last];
            theArray[last] = temp;
        }
        return theArray;
    }

    public static int indexofLargest(Comparable[] theArray, int size) {
        int indexSoFar = 0;
        for (int currIndex = 1; currIndex < size; currIndex++) {
            if (theArray[currIndex].compareTo(theArray[indexSoFar]) > 0) {
                indexSoFar = currIndex;
            }
        }
        return indexSoFar;
    }
}

public class Panel6 extends javax.swing.JPanel {

    /**
     * Creates new form Panel6
     */
    public Panel6() {
        initComponents();
        jTextArea3.setText(" Algorithm: SELECTION(A, N)\n"
                + " Repeat Step 2 and 3 for K = 1, 2,..., N - 1:\n"
                + " Call MIN (A, K, N, LOC)\n"
                + " [Interchange A[K] and P[LOC]\n"
                + " Set TEMP:= A[K], A[K]:=A[LOC] and A[LOC]:=TEMP\n"
                + " [End of Step 1 loop]\n"
                + " Exit");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(250, 250, 250));
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seletion Sort");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(250, 400));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 390, 400));

        jLabel2.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ข้อมูลหลังการจัดเรียง");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ข้อมูลก่อนการจัดเรียง");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jButton1.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jButton1.setText("ทำการจัดเรียง");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 140, -1));

        jLabel4.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Algorithm");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        jScrollPane4.setPreferredSize(new java.awt.Dimension(250, 400));

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] stringArray = jTextArea2.getText().split("\\s+");
        Comparable[] intArray = new Comparable[stringArray.length];

        for (int i = 0; i < stringArray.length; i++) {
            String intToString = stringArray[i];
            intArray[i] = Integer.parseInt(intToString);
            System.out.println("Data:" + intArray[i]);
        }
        SelectionSort al = new SelectionSort();
        al.selectionSort(intArray, intArray.length);
        jTextArea4.setText("");
        for (int i = 0; i < intArray.length; i++) {
            jTextArea4.setText(jTextArea4.getText() + " " + intArray[i].toString());
            System.out.println("Sorted Data:" + intArray[i]);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables

}
