/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectcos2103.Panel;

import java.awt.Font;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lymven
 */
// Double Linked List
class GroupOfData {

    String isbn;
    String book_name;
    String author;
    int amount;
    Float price;

    public GroupOfData(String a, String b, String c, int d, Float e) {
        isbn = a;
        book_name = b;
        author = c;
        amount = d;
        price = e;
    }
}

class QNode
{
    GroupOfData key;
    QNode next;
    
    public QNode(GroupOfData key) {
        this.key = key;
        this.next = null;
    }
    
    public Object getData() {
        return this.key;
    }
}

class Queue
{
    QNode front, rear;
    
    public Queue() {
        this.front = this.rear = null;
    }
    
    void enqueue(GroupOfData key)
    {
        QNode temp = new QNode(key);
        
        if(this.rear == null)
        {
            this.front = this.rear = temp;
        }
        
        this.rear.next = temp;
        this.rear = temp;
    }
    
    QNode dequeue() {
        if (this.front == null)
            return null;
        
        QNode temp = this.front;
        this.front = this.front.next;
        
        if (this.front == null)
            this.rear = null;
        return temp;
    }
}

public class Panel5 extends javax.swing.JPanel {

    // Should Make it OBJECT[] Array, but this is for an example
    void UpdateTable() {

        // Array Traversal
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        // Clear Row
        model.setRowCount(0);
        for (int i = 0; i < 10; i++) {
            model.addRow(new Object[] {});
        }
    }

    /**
     * Creates new form Panel3
     */
    public Panel5() {
        
        
        initComponents();
        jTable1.getTableHeader().setFont(new Font("TH Sarabun New", Font.BOLD, 18));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 360, -1));

        jTextField2.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 360, -1));

        jTextField3.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 360, -1));

        jTextField4.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 360, -1));

        jTextField5.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 360, -1));

        jButton1.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jButton1.setText("เพิ่มข้อมูลในคิว");
        jButton1.setMaximumSize(new java.awt.Dimension(150, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(150, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jButton3.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jButton3.setText("ลบข้อมูลออกจากคิว");
        jButton3.setMaximumSize(new java.awt.Dimension(150, 40));
        jButton3.setMinimumSize(new java.awt.Dimension(150, 40));
        jButton3.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        jTable1.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "ชื่อหนังสือ", "ชื่อผู้แต่ง", "จำนวนเล่ม", "ราคา"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 1020, 210));

        jLabel1.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ISBN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ชื่อหนังสือ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ชื่อผู้แต่ง");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("จำนวนเล่ม");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ราคา");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jButton6.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jButton6.setText("< Back");
        jButton6.setPreferredSize(new java.awt.Dimension(90, 40));
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jButton7.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jButton7.setText("Forward >");
        jButton7.setPreferredSize(new java.awt.Dimension(90, 40));
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //System.out.println(list);
        Queue q = new Queue();
        q.enqueue(new GroupOfData("123", "fgdfg", "ggdf", 32, 430.f));
        q.enqueue(new GroupOfData("124", "fgdfg", "ggdf", 32, 430.f));
        q.enqueue(new GroupOfData("125", "fgdfg", "ggdf", 32, 430.f));
        System.out.println(q.dequeue().getData());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
